<?php
/**
 * @date: 8/7/13
 * @uathor: viktor
 */

namespace gentoid\tests\route\BigInt;


class BigIntTest extends \PHPUnit_Framework_TestCase {

	protected $object;

	public function testCreate() {
		$this->object = new \gentoid\route\BigInt();
		$this->assertInstanceOf('BigInt', $this->object);
	}

	protected function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}
}
 